# Site Settings
title: Lisa's Resume
url: https://visalisa.github.io/lisa-resume/
baseurl: /lisa-resume #change it according to your repository name
about: True # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: ceramic # blue turquoise green berry orange ceramic


# Profile information
name: Lisa Jiamsirioungkul
tagline: VR Product Manager
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Energetic software engineer with 10+ years experience managing production for high-volume businesses. 
Increased code-efficiency of XYZ Corp customer portal by 55%.
Boosted customer retention by 25%. Spearheaded a team that won the 2016 BOSSIE Award for cloud computing.
An enthusiastic team player and deep creative thinker.'
# You can <a href="https://visalisa.github.io/lisa-resume/" target="_blank"download>download my resume here</a>
  
  

# Sidebar links
email: visakhalisajiam@gmail.com
phone: 562 396 3501
website: visalisa.com #do not add http://
linkedin: VisaLisa
github: visalisa
twitter: '@visalisago'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
analytics: UA-83979019-1

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 0.0.0.0
safe: false
